services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: bmi-backend

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    container_name: bmi-frontend

    
